In [1]:
import numpy as np

In [5]:
#create one diamensional array
x = np.array([40,60,70,90])
print(x)
print(type(x))
print(x.dtype)

[40 60 70 90]
<class 'numpy.ndarray'>
int32


In [7]:
#one character in array
x = np.array(["A",60,70,90])
print(x)
print(type(x))
print(x.dtype)

['A' '60' '70' '90']
<class 'numpy.ndarray'>
<U11


In [11]:
#one float value in array
x = np.array([4.4,60,70,90])
print(x)
print(type(x))
print(x.dtype)

[ 4.4 60.  70.  90. ]
<class 'numpy.ndarray'>
float64


In [13]:
#create 2D array
a2=np.array([[24,89],[34,59]])
print(a2)
print(type(a2))
print(a2.shape)

[[24 89]
 [34 59]]
<class 'numpy.ndarray'>
(2, 2)


In [17]:
#reshape of 1D array
p = np.array([40,60,70,90])
b = p.reshape(2,2)
print(b)
print(b.shape)

[[40 60]
 [70 90]]
(2, 2)


In [24]:
p = np.array([[24,89],[34,59]])
b = p.reshape(2,2)
print(b)
print(b.shape)

[[24 89]
 [34 59]]
(2, 2)


In [26]:
# create an array with arange()
c = np.arange(3,29)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28]


numpy.ndarray

In [32]:
# use of around ()
d =np.array([1.3467,2.10987,8.57])
print(np.around(d))

[1. 2. 9.]


In [34]:
#use astype() to convert the data type
a1 = np.array([[3,4,5,8],[7,2,8,np.NAN]])#np.NAN => numpy not a number
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [38]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [40]:
# mathematical operations on rows and colunms
a2 = np.array([[3,4,5],[7,9,20],[4,6,12]])
a2

array([[ 3,  4,  5],
       [ 7,  9, 20],
       [ 4,  6, 12]])

In [42]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))

[12 36 22]
[14 19 37]


In [46]:
# find the mean values along row and column
print(a2)
print(np.mean( a2,axis = 1))
print(np.mean(a2,axis = 0))

[[ 3  4  5]
 [ 7  9 20]
 [ 4  6 12]]
[ 4.         12.          7.33333333]
[ 4.66666667  6.33333333 12.33333333]


In [52]:
# matrix operations
a3= np.array([[3,4,5],[7,3,4],[4,6,2]])
print(a3)

np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 3 4]
 [4 6 2]]
[[0 4 5]
 [7 0 4]
 [4 6 0]]


In [64]:
# define two matrices
A = np.array([[3,4,5],[7,3,4]])
B = np.array([[3,4,5],[7,1,2]])
print(A.T)
print(B.T)

[[3 7]
 [4 3]
 [5 4]]
[[3 7]
 [4 1]
 [5 2]]


In [66]:
#accessing the array elements
a4=np.array([[3,4,5],[7,2,8],[9,1,6],[10,13,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10, 13, 18]])

In [68]:
a4[2][1]

1

In [70]:
#slicing of array first one row second one col
a4[:,1:]

array([[ 4,  5],
       [ 2,  8],
       [ 1,  6],
       [13, 18]])

In [86]:
a5=np.array([[3,4,5],[7,2,8],[9,1,6],[10,13,18]])
a5[1:3,0:2]

array([[7, 2],
       [9, 1]])